# Configures the stylesheet for Glow
# Will be replaced by a custom JSON file later on
style : "auto"

# Show local Markdown files only
local: true

# Disable mouse support in the terminal
mouse: false

# NOTE: Using a pager breaks the rendering for now.
# Refer to https://github.com/charmbracelet/glow/issues/296 for more info
# Use a pager to display the Markdown content
# pager: true

# Wrap content at a certain character limit
width: 90
